credentials:
  usernames:
    ivanyukpetro:
      email: i@gmail.com
      name: ivanyukpetro
      password: $2b$12$KxswNVR9TYyRW0z7YmObI.Pc8eHF5tY7idVc1tFOl7cQ0DjlxiMR.
    mariana.romanyshyn:
      email: m@grammarly.com
      name: mariana.romanyshyn
      password: $2b$12$U6FwiVQ5o2Krkrzf3BkmTukpcxzbVK4g6VSanXyn/7hjprnKNLZ3q
    ro.kovalch:
      email: r@gmail.com
      name: ro.kovalch
      password: $2b$12$dqBHeOfKfFW8MfTcW4h7H..WcKGjZWLMEZLdEsN/2fb50OgroHWvm
cookie:
  expiry_days: 30
  key: "ANNOTATION"
  name: "Annotation_Application"