credentials:
  usernames:
    ivanyukpetro:
      email: i@gmail.com
      name: ivanyukpetro
      password: $2b$12$KxswNVR9TYyRW0z7YmObI.Pc8eHF5tY7idVc1tFOl7cQ0DjlxiMR.
    mariana.romanyshyn:
      email: m@grammarly.com
      name: mariana.romanyshyn
      password: $2b$12$U6FwiVQ5o2Krkrzf3BkmTukpcxzbVK4g6VSanXyn/7hjprnKNLZ3q
    ro.kovalch:
      email: r@gmail.com
      name: ro.kovalch
      password: $2b$12$dqBHeOfKfFW8MfTcW4h7H..WcKGjZWLMEZLdEsN/2fb50OgroHWvm
    Maksimvodyanko:
      email: M@gmail.com
      name: Maksimvodyanko
      password: $2b$12$PwtBeRfflVjI7bOX2rfepu1TdlO.3Dn1qHBUQ.est0whqgaZxwkcy
    annaosvita2003:
      email: a@gmail.com
      name: annaosvita2003
      password: $2b$12$NukZT.5lAbf.9qbybf289OxOKLIYgib3mGkay2.7m53TXXSBu4P8.
    arsenij.lukashevskyj:
      email: a@outlook.com
      name: arsenij.lukashevskyj
      password: $2b$12$sIpfzeNTSEeJ1oo9iDeRLevXnVtNa2WjMqhMCSLqcffhkHdt8HMoa
    b.didenko:
      email: b@gmail.com
      name: b.didenko
      password: $2b$12$ZF/y1pBPk0LOvlug6Ryr4.H09ooMFq9apTFtWpJA0Q8P2eocRUR1K
    bodilowsky:
      email: b@gmail.com
      name: bodilowsky
      password: $2b$12$5IbSNrYHdEaM23SwXxITMe/ANlw.A3ENfSs74zgSdHN0OtHeQxvf2
    bohdanbeletskyi:
      email: b@gmail.com
      name: bohdanbeletskyi
      password: $2b$12$BlyC42qh3zt3dC5TQRe5c.0cPcRXKr6UQHomfZdUlSymQWMpqRUVG
    danilatv2001:
      email: d@gmail.com
      name: danilatv2001
      password: $2b$12$066A3S2JE3aXsNajfJjlXOJLskxgd69X8WSu2tfvBIAlLLLmgRXiC
    ebezverhna13:
      email: e@gmail.com
      name: ebezverhna13
      password: $2b$12$l7dGJV3w2nPCWjWo3Og5RuSaCb2fPgXpzm.e2.H7xFPl3YZprIOji
    kant2002:
      email: k@gmail.com
      name: kant2002
      password: $2b$12$U.vh8e1ZUtzH0c4JwecnGuwpfykN2TCpseeUt2LsGWSQG5w0HlLnq
    ll4236678:
      email: l@gmail.com
      name: ll4236678
      password: $2b$12$eL3vWJ5BNW4Vs.Akl0Ob..kM2Hk.eq6yKnKUDeLbFG3YDi5RamElW
    lmxlbm:
      email: l@gmail.com
      name: lmxlbm
      password: $2b$12$mAY1WoK3bIeQXBEJ6oCcoOpKTrZu9WL1bbtYZHWpHvkouljyFMKbS
    maria.morozova7474:
      email: m@gmail.com
      name: maria.morozova7474
      password: $2b$12$tHRWlZ.6rSqCHhYwlKV.f.y1sEDOslRmXAjdagpEGoYoABwFlNhOy
    marianamartyniv:
      email: m@gmail.com
      name: marianamartyniv
      password: $2b$12$0P48rzz6DZUkQS3FsGflEuq1FIf/pRQSJw1OlANzB.8X0zVlYdAZK
    myhajloolyzko2003:
      email: m@gmail.com
      name: myhajloolyzko2003
      password: $2b$12$gCwTLbnqzmjx2KdNXdhOL.Zdc0qCP4AFiT4KZfKnXSvg9KP9YPOqO
    n.vysokinskyi+annotations-uk:
      email: n@gmail.com
      name: n.vysokinskyi+annotations-uk
      password: $2b$12$Sz1R73J59WcC4TQGQQ7b3eh/n0nJAVRHipiu5Pc4uR4W6dHZbLJxa
    nataliia.sheremett:
      email: n@gmail.com
      name: nataliia.sheremett
      password: $2b$12$FY8eNSSFlwLu66LoXREWK.znRy81WRfBUi3d7gfoQe.vmp6q4m4I6
    petrov.jurij.b24nf:
      email: p@kmf.org.ua
      name: petrov.jurij.b24nf
      password: $2b$12$0xJacPDy.DbQ.nrnFNg3zuEH8Y61DHZuIz.HUlC2GUwiGRezE4MIa
    romaniukolena4545:
      email: r@gmail.com
      name: romaniukolena4545
      password: $2b$12$HBL6zONAmXUwIT2V/e.06OocIDwbrHbY/Hchb1aBmvex..JKtD.Ge
    ruda.andrii:
      email: r@gmail.com
      name: ruda.andrii
      password: $2b$12$QzA2PeaT5U4ywnRq60jfwecFt8NXP16WOCEdKvdrXHbf5pdUaEs1K
    sophionysko:
      email: s@gmail.com
      name: sophionysko
      password: $2b$12$yu5DZznWTTocbIp/9ZKVJOFxD2MdHIqz/bqeNZ4t0Yn.pfGXFba2S
    tamila.krashtan:
      email: t@gmail.com
      name: tamila.krashtan
      password: $2b$12$9n6XSGXn6pdju3QeZQdu3Ox16qAzKCSOWzfUXvW5nMLfD5uGL/1c.
    veronicamorrr:
      email: v@gmail.com
      name: veronicamorrr
      password: $2b$12$i1An4CP8tnPr0RJdjlDuturAgMFTVb9RHXi3ITzcWqlbkcBsu4ZmG
    zhannavoloshko:
      email: z@gmail.com
      name: zhannavoloshko
      password: $2b$12$sZ7vv8esxh2lNy2FOBDog.z2f38ZEsbJkdPFbVSST9VOo8vKtkJWi
cookie:
  expiry_days: 30
  key: "ANNOTATION"
  name: "Annotation_Application"